site_name: RUN Art Foundry — Briefing Privado
site_url: https://example.pages.dev/
site_description: Micrositio privado para documentación, auditorías y toma de decisiones con el cliente.
repo_name: runart-briefing
theme:
  name: material
  language: es
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.action.edit
    - search.suggest
  palette:
    scheme: default
    primary: indigo
    accent: light blue
  custom_dir: overrides
extra:
  generator: false
  social: []
  # Paleta placeholder, ajustable más adelante vía CSS si se requiere.
  nav_internal:
    - title: "Editor de Fichas (beta)"
      class: interno
    - title: "Inbox"
      class: interno
    - title: "Exportaciones (MF)"
      class: interno
nav:
  - Inicio: index.md
  - Operación:
      - Entornos: internal/briefing_system/ops/environments.md
      - "Tablero vivo": internal/briefing_system/ops/status.md
      - "Historial de cambios": internal/briefing_system/ops/changelog.md
      - "Registro de incidentes": internal/briefing_system/ops/incidents.md
  - Plan & Roadmap: client_projects/runart_foundry/plan/index.md
  - Fases: fases/index.md
  - Auditoría: client_projects/runart_foundry/auditoria/index.md
  - Proceso: proceso/index.md
  - Decisiones:
      - Índice de decisiones: decisiones/index.md
      - Contenido sitio viejo (brief): decisiones/contenido-sitio-viejo.md
      - "Ficha de Proyecto (formulario)": decisiones/ficha-proyecto.md
  - Galería: galeria/index.md
  - Inbox (Decisiones):
      - "Bandeja general": inbox/index.md
      - "Fichas recibidas": inbox/fichas.md
  - Dashboards:
      - "KPIs (cliente)": dashboards/cliente.md
  - Acerca: acerca/index.md
  - Reportes:
      - Reportes (cliente):
          - "Master Plan (Estrategia)": client_projects/runart_foundry/reports/2025-10-02_master_plan.md
          - "Arquitectura": briefing_arquitectura.md
          - "Corte de Control — Fase 2": client_projects/runart_foundry/reports/corte_control_fase2.md
          - "Notas de Release (ARQ)": client_projects/runart_foundry/reports/ARQ_RELEASE_NOTES.md
      - "Corte Fase ARQ": client_projects/runart_foundry/reports/corte_arq.md
      - "Mapa de interfaces (ARQ)": arq/mapa_interfaces.md
  - Reportes (interno):
      - "Bitácora del briefing": client_projects/runart_foundry/reports/README.md
      - "Auditoría inventario (2025-10-02)": client_projects/runart_foundry/reports/2025-10-02_repo_inventory.md
  - Herramientas:
      - "Editor de Fichas (beta)": editor/index.md
      - "Inbox": inbox/index.md
      - "Exportaciones (MF)": exports/index.md
  - Documentación:
      - "ADR-0001 — Briefing como panel interno": client_projects/runart_foundry/reports/adr/ADR-0001_briefing_como_panel_interno.md
      - "Plan — Sistema Briefing (ARQ)": client_projects/runart_foundry/reports/plan_fase_arq.md
      - "Fase 1 — Control de Fichas": client_projects/runart_foundry/reports/fase1_fichas.md
      - "Permisos finos por rol": accesos/permisos.md
      - Operaciones:
          - "CI & gates": internal/briefing_system/ops/ci.md
          - "Banderas de entorno": internal/briefing_system/ops/environments.md
  - Arquitectura:
    - "Índice": internal/briefing_system/architecture/_index.md
    - "000 — Resumen ejecutivo": internal/briefing_system/architecture/000_overview.md
    - "010 — Inventario actual": internal/briefing_system/architecture/010_inventory.md
    - "020 — Estructura objetivo": internal/briefing_system/architecture/020_target_structure.md
    - "030 — Convenciones y estándares": internal/briefing_system/architecture/030_conventions.md
    - "040 — Workflows compartidos": internal/briefing_system/architecture/040_ci_shared.md
    - "050 — Targets Make": internal/briefing_system/architecture/050_make_targets.md
    - "060 — Plan de migración": internal/briefing_system/architecture/060_migration_plan.md
    - "065 — Switch Cloudflare Pages": internal/briefing_system/architecture/065_switch_pages.md
    - "070 — Registro de riesgos": internal/briefing_system/architecture/070_risks.md
  - "Guía de estilos UI": ui/estilos.md
  - Proyectos:
      - "Índice de proyectos": projects/index.md
      - "Plantilla Ficha Técnica (YAML)": projects/_template.yaml
      - "Esquema de fichas (YAML)": projects/schema.yaml
      - "Proyectos piloto (ES)":
          - "Mons. Román (2015)": projects/mons-roman-2015.yaml
          - "Raider (2018)": projects/raider-2018.yaml
          - "Colaboración internacional (2018)": projects/colaboracion-internacional-01.yaml
      - "Pilot projects (EN)":
          - "Monsignor Agustín Román (2015)": projects/en/mons-roman-2015.yaml
          - "Raider (2018)": projects/en/raider-2018.yaml
          - "International collaboration (2018)": projects/en/colaboracion-internacional-01.yaml
      - "Proyectos intermedios (ES)":
          - "Carole A. Feuerman (2019)": projects/carole-feuerman-2019.yaml
          - "Roberto Fabelo (2016)": projects/roberto-fabelo-2016.yaml
          - "Pedro Pablo Oliva (2017)": projects/pedro-pablo-oliva-2017.yaml
          - "Williams Carmona (2019)": projects/williams-carmona-2019.yaml
          - "The-Merger (2020)": projects/the-merger-2020.yaml
          - "Lawrence Holofcener (2015)": projects/lawrence-holofcener-2015.yaml
          - "Proyecto Messi (2024)": projects/proyecto-messi-2024.yaml
      - "Intermediate projects (EN)":
          - "Carole A. Feuerman (2019)": projects/en/carole-feuerman-2019.yaml
          - "Roberto Fabelo (2016)": projects/en/roberto-fabelo-2016.yaml
          - "Pedro Pablo Oliva (2017)": projects/en/pedro-pablo-oliva-2017.yaml
          - "Williams Carmona (2019)": projects/en/williams-carmona-2019.yaml
          - "The-Merger (2020)": projects/en/the-merger-2020.yaml
          - "Lawrence Holofcener (2015)": projects/en/lawrence-holofcener-2015.yaml
          - "Messi Project (2024)": projects/en/proyecto-messi-2024.yaml
  - Press-kit:
      - "Press-kit v0 (ES)": client_projects/runart_foundry/reports/presskit_v0.md
      - "Press-kit v1 (ES)": client_projects/runart_foundry/reports/presskit_v1_ES.md
      - "Press-kit v1 (EN)": client_projects/runart_foundry/reports/presskit_v1_EN.md
  - Smoke Test: _smoke.md
plugins:
  - search
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path:
        - ..
        - ../..
extra_css:
  - assets/extra.css
  - assets/runart/userbar.css
extra_javascript:
  - assets/env-flag.js
  - assets/runart/userbar.js
# Evitar indexación por robots: robots.txt + meta en overrides/main.html
