name: Auto Open PR on Deploy Branches

on:
  push:
    branches:
      - "deploy/**"
      - "deploy/*"

permissions:
  contents: write
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract branch name
        id: vars
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Ensure PR exists (create if missing)
        id: ensure_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = '${{ steps.vars.outputs.branch }}';
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const prs = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              head: `${owner}:${branch}`,
              base: 'main',
            });

            if (prs.data.length > 0) {
              core.info(`PR ya existe: #${prs.data[0].number}`);
              core.setOutput('pr_number', prs.data[0].number.toString());
              return;
            }

            const title = `deploy: ${branch} (Cloudflare Pages)`;
            const body = [
              `Release desde rama **${branch}**`,
              `- Validaciones locales: lint/build/env PASS`,
              `- Tag relacionado (si aplica): briefing-cleanup-20251007`,
              `- Bitácora: apps/briefing/docs/082_reestructuracion_local.md`,
              `- Changelog: apps/briefing/CHANGELOG.md`
            ].join('\n');

            try {
              const pr = await github.rest.pulls.create({
                owner,
                repo,
                head: branch,
                base: 'main',
                title,
                body,
                maintainer_can_modify: true,
              });
              core.info(`PR creado: #${pr.data.number}`);
              core.setOutput('pr_number', pr.data.number.toString());
            } catch (error) {
              const message = error?.message || '';
              if (error?.status === 403 && message.includes('not permitted to create or approve pull requests')) {
                core.setFailed('El token actual no puede crear PRs. Activa "Allow GitHub Actions to create and approve pull requests" en Settings → Actions → General.');
                return;
              }
              throw error;
            }

      - name: Add labels
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = '${{ steps.vars.outputs.branch }}';
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const prs = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              head: `${owner}:${branch}`,
              base: 'main',
            });

            if (prs.data.length === 0) {
              core.info('No se encontraron PRs para etiquetar.');
              return;
            }

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prs.data[0].number,
              labels: ['deploy', 'pages', 'preview'],
            });
