name: Auto-merge on label

on:
  pull_request_target:
    types: [opened, labeled, ready_for_review, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  enable-auto-merge:
    # Auto-merge si el PR tiene cualquiera de estas etiquetas
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge') || contains(github.event.pull_request.labels.*.name, 'ready-for-production')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (squash)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash
