name: build-wpcli-bridge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Package plugin
        run: |
          set -euo pipefail
          cd tools/wpcli-bridge-plugin
          VERSION="v1.0.${{ github.run_number }}"
          ZIP_NAME="runart-wpcli-bridge-${VERSION}.zip"
          zip -r "$ZIP_NAME" . -x "*.DS_Store"
          echo "ZIP=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: runart-wpcli-bridge
          path: tools/wpcli-bridge-plugin/${{ env.ZIP }}
