name: Verify Production (Briefing)

on:
  workflow_run:
    workflows: ["Deploy to Cloudflare Pages (Briefing)"]
    types: [completed]

permissions:
  contents: write

jobs:
  verify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check / (home)
        run: |
          curl -sSf https://runart-foundry.pages.dev/ >/dev/null

      - name: Check /status/
        run: |
          curl -sS https://runart-foundry.pages.dev/status/ | grep -E "KPIs|Documentos|Estado Operativo" >/dev/null

      - name: Check /news/
        run: |
          curl -sS https://runart-foundry.pages.dev/news/ | grep -E "Auto-Post|Actualización|docs|news" >/dev/null

      - name: Check /status/history/
        run: |
          curl -sS https://runart-foundry.pages.dev/status/history/ | grep -E "canvas|Chart" >/dev/null

      - name: Log verification to meta
        run: |
          echo "" >> docs/_meta/BRIEFING_STATUS_PIPELINE_RUN.md
          echo "- Verificación post-deploy OK: $(date -u +%FT%TZ)" >> docs/_meta/BRIEFING_STATUS_PIPELINE_RUN.md
          echo "  Rutas verificadas: /, /status/, /news/, /status/history/" >> docs/_meta/BRIEFING_STATUS_PIPELINE_RUN.md

      - name: Commit verification log
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/_meta/BRIEFING_STATUS_PIPELINE_RUN.md
          git commit -m "docs(meta): log post-deploy verification [skip ci]" || true
          git push || true
