name: Rotate Application Password

on:
  workflow_dispatch: {}

jobs:
  rotate:
    name: Rotate WP Application Password
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.WP_BASE_URL }}
      WP_USER: ${{ secrets.WP_USER }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
      SUMMARY_FILE: rotate-app-password_summary.txt
    steps:
      - name: Instrucciones para operador
        run: |
          echo "1) Crear NUEVO Application Password en WP-Admin para el usuario configurado." \
               "2) Actualizar el secreto WP_APP_PASSWORD en GitHub repo/org." \
               "3) Re-ejecutar este workflow para validar."

      - name: Validar users/me
        id: validate
        run: |
          CODE=$(curl -sS -o /dev/null -w "%{http_code}" -u "$WP_USER:$WP_APP_PASSWORD" "$BASE_URL/wp-json/wp/v2/users/me") || true
          printf "Rotación exitosa; última validación=%s; code=%s\n" "$(date -u +%FT%TZ)" "$CODE" | tee "$SUMMARY_FILE"
          if [ "$CODE" != "200" ]; then
            echo "::error::Validación falló (esperado 200)."; exit 1; fi

      - name: Upload summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: rotate-app-password-summary
          path: ${{ env.SUMMARY_FILE }}
